### ISSUE TITLE
learningr package not avaliable for R v3

### ISSUE THREAD

**Issue by chrisalbon** [richierocks/learningr#1]
I'm getting this error while loading the learningr package while working through the book:

> install.packages("learningr")
> Warning in install.packages :
>   package ‘learningr’ is not available (for R version 3.0.2)

**Comment by chrisalbon** [comment]
Ah, now I understand my error. It isn't in CRAN yet.

**Comment by richierocks** [comment]
Hi Chris,

Sorry for not getting back to you sooner.  There were a few technical
issues with getting the package on CRAN.  I've just uploaded it tonight, so
it should appear in the next couple of days.

In the meantime, you can access the development version on github:

https://github.com/richierocks/learningr

I hope that you are enjoying the book.

On 2 November 2013 18:12, Chris R. Albon notifications@github.com wrote:

> Ah, now I understand my error. It isn't in CRAN yet.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richierocks/learningr/issues/1#issuecomment-27627631
> .

## 

Regards,
Richie

Learning R http://shop.oreilly.com/product/0636920028352.do
4dpiecharts.com

**Comment by chrisalbon** [comment]
Hey Richard,

Great book. I went through it over ~20 hours last weekend. I’m not learning R from scratch, but was looking for a refresher after a year at a non-coding job.  

## 

Chris R. Albon
